Marketplace-of-telegram-bots-for-retail/frontend

src/components/PopupImage/PopupImage.css, src/components/PopupImage/PopupImage.jsx, src/components/ProductDetail/ProductDetail.jsx, src/components/ProductPhotos/ProductPhotos.css, src/components/ProductPhotos/ProductPhotos.jsx, src/components/ProductReviewInitial/ProductReviewInitial.css, src/components/ProductReviewInitial/ProductReviewInitial.jsx, src/components/ProductReviews/ProductReviews.css, src/hooks/usePopupClose.js, src/images/arcticons_photo-and-picture-resizer.svg
Добавила функциональность кнопкам и элементам на странице
=> [/] add functional on product page

src/components/PopupImage/PopupImage.jsx, src/components/Product/Product.jsx, src/components/ProductDescription/ProductDescription.jsx, src/components/ProductDetail/ProductDetail.jsx, src/components/ProductDetails/ProductDetails.jsx, src/components/ProductPhotos/ProductPhotos.css, src/components/ProductPhotos/ProductPhotos.jsx, src/components/ProductPrice/ProductPrice.jsx, src/components/ProductPriceBlock/ProductPriceBlock.jsx, src/components/ProductTitle/ProductTitle.jsx
Добавила карточку из массива на страницу продукта
Добавила скрол на карточки в маленьком разрешении, функционал кнопки прокрутки
По нажатию на маленькую фотографию она отображается в большом размере
=> [/] add cards and scroll on product page

src/components/App/App.jsx, src/components/Content/Content.jsx, src/components/Dropdown/Dropdown.jsx, src/components/Showcase/Showcase.jsx, src/utils/Api.js
=> Fix API, Fix Like

src/components/App/App.jsx, src/components/Favorites/Favorites.jsx
Добавление карточек на страницу избранные
=> Add favorute pageCards

src/components/App/App.jsx, src/components/AuthButtons/AuthButtons.jsx, src/components/AuthModal/AuthModal.jsx, src/components/Header/Header.jsx, src/components/Login/Login.jsx
немного поломала логику стейта isAuthorized т.к. jwt  при логине сохраняется только при отметке чекбокса, надо будет исправить
=> add closing AuthButtons modal after login

src/components/App/App.jsx, src/components/Login/Login.jsx
=> delete changes in cbLogIn

src/components/ProductDescription/ProductDescription.jsx, src/components/ProductInfo/ProductInfo.jsx, src/components/ProductReviewInitial/ProductReviewInitial.jsx
Исправила описание продукта
Исправила В избранное
=> [/] add description on product page

src/components/PopupImage/PopupImage.css, src/components/ProductDescription/ProductDescription.css, src/components/ProductDescription/ProductDescription.jsx, src/components/ProductPhotos/ProductPhotos.jsx
Добавила скрытие блока с видео, если видео в базе данных продукта отсутствует
=> [/] add hide video

src/components/Product/Product.jsx, src/components/Product/ProductDetail/ProductDetail.css, src/components/Product/ProductDetail/ProductDetail.jsx, src/components/Product/ProductDetails/ProductDetails.jsx, src/components/Product/ProductReviewInitial/ProductReviewInitial.jsx, src/components/Product/ProductReviews/ProductReviews.jsx, src/components/Product/ReviewCard/ReviewCard.jsx, src/utils/Api.js
Добавила показ отзывов свыше 3
=> [/] add show more reviews

src/components/Product/Product.jsx, src/components/Product/ProductReviewInitial/ProductReviewInitial.jsx, src/components/Rating/Rating.jsx
Создала апи добавления отзыва на странице Product строка 46
=> [/] add create review

src/components/Product/Product.css, src/components/Product/Product.jsx, src/components/Product/ProductDetail/ProductDetail.jsx, src/components/Product/ProductDetails/ProductDetails.jsx, src/components/Product/ProductInfo/ProductInfo.jsx, src/components/Product/ProductPrice/ProductPrice.css, src/components/Product/ProductPrice/ProductPrice.jsx, src/components/Product/ProductReviewInitial/ProductReviewInitial.jsx, src/components/Product/ProductReviews/ProductReviews.css, src/components/Product/ProductReviews/ProductReviews.jsx, src/components/Product/ReviewCard/ReviewCard.jsx, src/components/Rating/Rating.jsx
Отображение отзывов
Добавление отзыва
Отправка отзыва после проставления рейтинга
Отображение рейтингов согласно макета
Добавила универсальную кнопку В корзину
=> [/] test api create review

src/components/App/App.jsx, src/utils/Api.js, src/utils/tokenStorage.js
=> add feature remember me

src/components/showcase/More/More.jsx, src/components/showcase/Showcase/Showcase.jsx, src/hooks/useScroll.js
Добавил загрузку карточек по скролу
=> add scrolling map loading

src/components/Product/Product.jsx, src/components/Product/ProductDetail/ProductDetail.jsx, src/components/Product/ProductDetails/ProductDetails.jsx, src/components/Product/ProductInfo/ProductInfo.jsx, src/components/Product/ProductReviewInitial/ProductReviewInitial.jsx, src/components/Product/ProductReviews/ProductReviews.jsx, src/components/Product/ReviewCard/ReviewCard.jsx, src/components/Rating/Rating.css, src/components/Rating/Rating.jsx
Добавила перевод на блок с отзывами при клике на рейтинг в ProductInfo
=> [/] add click on rating product info

src/components/Product/ReviewCard/ReviewCard.jsx
=> [/] parse date in reviews

src/components/Product/Product.jsx, src/components/Product/ProductDetail/ProductDetail.jsx, src/components/Product/ProductDetails/ProductDetails.jsx, src/components/Product/ProductReviewInitial/ProductReviewInitial.jsx, src/components/Product/ProductReviews/ProductReviews.jsx
Подключила редактирование отзыва
=> [/] edit review

src/components/Card/Card.jsx, src/components/Product/ProductReviewInitial/ProductReviewInitial.jsx
Добавила фокус наверх страницы при переходе на страницу продукта
=> [/] add focus up on product page

src/components/Product/Product.jsx, src/components/Product/ProductDetail/ProductDetail.css, src/components/Product/ProductDetail/ProductDetail.jsx, src/components/Product/ProductDetails/ProductDetails.jsx, src/components/Product/ProductReviewInitial/ProductReviewInitial.css, src/components/Product/ProductReviewInitial/ProductReviewInitial.jsx, src/components/Product/ProductReviews/ProductReviews.css, src/components/Product/ProductReviews/ProductReviews.jsx, src/components/Product/ReviewCard/ReviewCard.css, src/components/Product/ReviewCard/ReviewCard.jsx, src/utils/Api.js
Добавила удаление отзыва
Поправила верстку согласно отредактированного макета
=> [/] add delete review

src/components/Cart/CartCard/CartCard.jsx, src/components/Cart/CartTemp.jsx, src/components/Product/ProductPrice/ProductPrice.jsx
Поправила CartCard под получение данных с бека
Подключила к CartTemp
=> [/] add CartCard to CartTemp

src/components/Cart/Cart.jsx, src/components/Cart/CartCard/CartCard.css, src/components/Cart/CartCard/CartCard.jsx, src/components/Cart/CartItem/CartItem.css, src/components/Cart/CartItem/CartItem.jsx
=> [/] edit layout cart

src/components/App/App.jsx
Добавила компонент Goods  в App
=> [/] add goods page

src/components/profile/index.css, src/components/profile/index.jsx, src/components/profile/seller/ProfileLegalForm/ProfileLegalForm.jsx, src/components/profile/user/ProfileForm/index.jsx
редактирование страницы профиля в ЛК
=> fix Profile

src/components/info/AboutMain/AboutMain.css, src/components/info/AboutMain/AboutMain.jsx
добавила кнопку в блок "О маркетплейсе"
=> add button

src/components/personal/goods/Goods.jsx, src/components/personal/goods/GoodsNewBot/GoodsNewBot.css, src/components/personal/goods/GoodsNewBot/GoodsNewBot.jsx, src/hooks/useFormAndValid.js
Добавила действия инпутам и валидацию
=> [/] add actions inputs

src/components/personal/seller/SellerLegalData/index.jsx, src/components/personal/user/ProfileFormButtons/index.jsx
исправила баг при выборе банка в компоненте SellerLegalData
изменила пути в компоненте ProfileFormButtons для очистки формы на стр юр.инф.
=> fix SellerLegalData: add handleIndexChange and fix location

src/components/Cart/CartCard/CartCard.css, src/components/Cart/CartCard/CartCard.jsx, src/components/personal/goods/Goods.jsx
добавила страницу Мои товары в ЛК Продавца
редактирование карточки бота в компоненте CartCard
=> add GoodBots and fix CartCard

src/components/App/App.jsx, src/components/Cart/CartCard/CartCard.jsx, src/components/Header/Header.jsx, src/components/Modal/ConfirmDeleteProfileModal/index.jsx, src/components/Modal/ConfirmLogoutModal/index.jsx, src/components/Modal/index.jsx, src/components/auth/AuthButtons/AuthButtons.jsx, src/components/personal/ProfileNavigation/index.jsx, src/components/personal/seller/SellerLegalData/index.jsx, src/components/personal/user/ProfileAvatar/index.jsx, src/hooks/useHookUpModals.js, src/hooks/useModal.js, src/store/actions.js, src/store/index.js, src/store/modalsSlice.js, src/store/selectors.js, src/store/userSlice.js, src/utils/Api.js
- Теперь useModal у нас работает только на данных из store (указала в комментах)
- Компонент Modal принимает немного другие аргументы, в комментах более подробно описала каждый. 
- Т.к. Катя использует его у себя в двух компонентах(SellerLegalData и CartCard ), я немного отрефакторила. Вроде все работает (Кать, можешь проверить)
- сделала отдельный слайс для модалок modalsSlice, вынесла модалки в store
- сделала отдельный хук для подключения сразу всех модалок хуком useModal, подключила в App
- пофиксила баг с незагружающимися картинками весом более 3 МБ
=> refactor modals, fix bug in avatar

src/components/personal/goods/GoodsNewBot/GoodsNewBot.css, src/components/personal/goods/GoodsNewBot/GoodsNewBot.jsx, src/components/popups/PopupCategory/PopupCategory.css, src/components/popups/PopupHint.css, src/components/popups/PopupName/PopupName.css
Поправила попапы, сделала по наведению мыши.
=> [/] edit popups on new bot page
